name: bagi_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  animate_do: ^2.1.0
  dartz:
  flutterfire_ui:
  path_provider:
  image_picker:
  equatable:
  get_storage:
  dio:
  auto_size_text:
  persian_number_utility:
  connectivity_plus:
  flutter_font_icons:

  get:
  package_info_plus:
  shamsi_date:
  logger:
  flutter_svg:
  flutter_spinkit: ^5.1.0
  mobx: ^2.0.7+5
  rxdart:
  video_player:
  get_it:
  flutter_mobx: ^2.0.6+1
  firebase_storage:
  intl:
  flutter_map:
  flutter_chat_bubble:
  cupertino_list_tile:
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  firebase_auth: ^3.7.0
  cloud_functions: ^3.3.6
  giff_dialog: ^1.0.1
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/.
    - assets/images/.
    - assets/images/icons/.
    - assets/images/pictures/.


  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/OutfitSemiBold.ttf
