import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_Us': {
          "Cancel" : "Cancel",
          "Please wait" : "Please wait",
          'Choose Days': 'Choose Days',
          'Choose Devices': 'Choose Devices',
          'Shahrino': 'Shahrino',
          'Access': 'Access',
          'Gardens': 'Gardens',
          'Transportation': 'Transportation',
          'Irrigation': 'Irrigation',
          'Multi-floor parking': 'Multi-floor parking',
          'Park Lighting': 'Park Lighting',
          'passages Lighting': 'passages Lighting',
          'CCTV': 'CCTV',
          'Air purification': 'Monitoring the weather',
          'edit': 'Edit',
          'delete': 'Delete',
          'Reports': 'Reports',
          'Profile': 'Profile',
          'Mac': 'Mac-Address',
          'There are no items to display': 'There are no items to display',
          'Address': 'Address',
          'Area': 'Area',
          'List': 'List',
          'Scenarios': 'Scenarios',
          'Scenario': 'Scenario',
          'Devices': 'Devices',
          'Device': 'Device',
          'No information recorded': ' - ',
          'Disabled': 'Disabled',
          'Enabled': 'Enabled',
          'Number of devices': 'Number of devices',
          'designed and developed by iot': 'Designed and developed by HooshmandNegar – 2022',
          'Login': 'Login',
          'UserName': 'UserName',
          'Password': 'Password',
          'Loading': 'Loading',
          'Failed': 'Failed',
          'Success': 'Success',
          'Confirm': 'Confirm',
          'Logout': 'Logout',
          'PhoneNumber': 'Phone Number',
          'NationalCode': 'National Code',
          'FirstName': 'First Name',
          'LastName': 'Last Name',
          'Email': 'Email',
          'Optional': '(Optional)',
          'Settings': 'Settings',
          'DeviceCount': 'Device Count',
          'Name': 'Name',
          'Muted': 'Muted',
          'Add Garden': 'Add Garden',
          'Status': 'Status',
          'Type': 'Type',
          'Smart': 'Smart',
          'Automatic': 'Automatic',
          'Manual': 'Manual',
          'New Scenario': 'New Scenario',
          'Lighting': 'Lighting',
          'On': 'On',
          'Off': 'Off',
          'MacAddress': 'MacAddress',
          'New Device': 'New Device',
          'Edit Device': 'Edit Device',
          'Actuator': 'Actuator',
          'Sensor': 'Sensor',
          'TYPE': 'Type',
          'Irrigation Actuator': 'Irrigation Actuator',
          'Lighting Actuator': 'Lighting Actuator',
          'Irrigation Sensor': 'Irrigation Sensor',
          'Lighting Sensor': 'Lighting Sensor',
          "Category": "Category",
          "Device Type": "Device Type",
          "Manage Scenario": "Manage Scenario",
          'Every Day': 'Every Day',
          'Start': 'Start',
          'Start Time': 'Start Time',
          'End Time': 'End Time',
          'Duration': 'Duration',
          'Start & End Period': 'Start & End Period',
          'Scenario Name': 'Scenario Name',
          'To': ' To ',
          "saturday": "Saturday",
          "sunday": "Sunday",
          "monday": "Monday",
          'tuesday': "Tuesday",
          'wednesday': "Wednesday",
          'thursday': "Thursday",
          "friday": "Friday",
          "Zone" : 'Zone',
          "Not registered" : 'Not registered',
          "Zones" : 'Zones',
          "There is no part in this Garden" : "There is no part in this Garden",
          "Add a Zone" : "Add a Zone",
          "Moisture content" : "Moisture content",
          "Available devices" : 'Available devices',
          "Amount of lighting" : "Amount of lighting",
          "Choose" : "Choose",
          "NoDiyar" : 'NewDiyar' ,
          "ScenarioCount" : 'Scenario Count' ,
          "New" : 'New' ,
          "Available" : 'Available' ,
          "Edit Zone" : 'Edit Zone' ,
          "New Zone" : 'New Zone' ,
          "Equipment" : 'Equipment' ,
          "There is no sensor in this section" : 'There is no sensor in this section' ,
          'No information to display' : 'No information to display',
          'Role' : 'Role',
          'Version' : 'Version',
          'Manager' : 'Manager',
          'List of devices' : 'List of devices',
          'Turn it all on' : 'Turn it all on',
          'Turn it all off' : 'Turn it all off',
          "Select devices" : "Select devices",
          "Choosing days" : "Choosing days",
          "Max" : 'Max',
          "Average" : 'Average',
          "Min" : 'Min',
          "Update" : 'Update',
          "The new version is available" : 'The new version is available',
          "New Version" : 'New Version',
          "Later" : 'Later',
          "Workers" : "Curators",
          "attention" : 'Attention',
          "Turn on all devices in this section ?" : "Turn on all devices in this section ?",
          "Turn off all devices in this section ?" : "Turn off all devices in this section ?",
          "There is no worker in this garden" : "There is no Curator in this garden",
          "Add a worker" : "Add a Curator",
          "Select User" : "Select User",
          "mayor" : "Mayor",
          "manager" : "Manager",
          "district" : "Mayor of the region",
          "labor" : "Curator",
          "Users" : "Users",
          "Manage Users" : "Manage Users",
          "Access level" : "Access level",
          "New User" : "New User" ,
          "Edit User" : "Edit User" ,
          "Select Role" : "Select Role" ,
          "worker" : 'Curator',
          "Are you sure  ?" : 'Are you sure  ?',
          "Managers" : "Managers",
          "Add a manager" : "Add a manager",
          "There is no manager for this garden" : "There is no manager for this garden",
          "close" : "Close" ,
          "Information" : "Information" ,
          "Refining Sensor" : "Refining Sensor",
          "Carbon dioxide" : "Carbon dioxide",
          "Carbon monoxide" : "Carbon monoxide",
          "Ozone" : "Ozone",
          "Noise" : "Noise",
          "Particles" : "Particles",
        },
        'fa_IR': {

          "Please wait" : "لطفا صبر کنید",
          "Carbon dioxide" : "کربن دی اکسید",
          "Carbon monoxide" : "کربن مونو اکسید",
          "Ozone" : "اوزون",
          "Noise" : "آلودگی صوتی",
          "Particles" : "ذرات معلق",
  "Refining Sensor" : "سنسور پایش",
          "close" : "بستن" ,
          "Information" : "اطلاعات" ,
          "There is no manager for this garden" : "مدیری برای این بوستان وجود ندارد",
          "Managers" : "مدیران",
          "Select User" : "انتخاب کاربر",
          "Select Role" : "انتخاب نقش" ,
          "Edit User" : "ویرایش کاربر" ,
          "New User" : "کاربر جدید" ,
          "Access level" : "سطح دسترسی",
          "Users" : "کاربران",
          "Manage Users" : "مدیریت کاربران",
          "mayor" : "شهردار",
          "manager" : "مدیر",
          "district" : "شهردار منطقه",
          "labor" : "متصدی",
          "Add a worker" : "یک متصدی اضافه کنید",
          "Add a manager" : "یک مدیر اضافه کنید",
          "There is no worker in this garden" : "متصدی در این بوستان وجود ندارد",
          "Workers" : "متصدیان",
          "Update" : 'بروزرسانی',
          "The new version is available" : 'نسخه جدید در دسترس است',
          "New Version" : 'نسخه جدید',
          "Later" : 'بعدا',
          "worker" : 'متصدی',
          "Are you sure  ?" : 'آیا مطمئن هستید ؟',
          "Turn on all devices in this section ?" : "تمام دستگاه ها در این بخش روشن شود ؟",
          "Turn off all devices in this section ?" : "تمام دستگاه ها در این بخش خاموش شود ؟",
          "attention" : 'توجه',
          "Cancel" : 'لغو',
          "Max" : 'ماکسیمم',
          "Average" : 'میانگین',
          "Min" : 'مینیمم',
          "Choosing days" : "انتخاب روزها",
          "Select devices" : "انتخاب دستگاه ها",
          'List of devices' : 'لیست دستگاه ها',
          'Turn it all on' : 'روشن کردن همه',
          'Turn it all off' : 'خاموش کردن همه',
          'Role' : 'نقش',
          'Version' : 'نسخه',
          'Manager' : 'مدیر',
          'No information to display' : 'اطلاعاتی برای نمایش وجود ندارد',
          "Equipment" : 'تجهیزات' ,
          "There is no sensor in this section" : 'سنسوری در این بخش وجود ندارد' ,
          "Edit Zone" : 'ویرایش بخش' ,
          "New Zone" : 'بخش جدید' ,
          "New" : 'جدید' ,
          "Available" : 'موجود' ,
          "ScenarioCount" : 'تعداد سناریوها' ,
          "NoDiyar" : 'نودیار' ,
          "Choose" : "انتخاب کنید",
          "Moisture content" : "میزان رطوبت",
          "Amount of lighting" : "میزان روشنایی",
          "There is no part in this Garden" : "بخشی در این بوستان وجود ندارد",
          "Add a Zone" : "یک بخش اضافه کنید",
          "Zones" : 'بخش ها',
          "Zone" : 'بخش',
          "Not registered" : 'ثبت نشده است',
          "saturday": "شنبه",
          "sunday": "یکشنبه",
          "monday": "دوشنبه",
          'tuesday': "سه شنبه",
          'wednesday': "چهارشنبه",
          'thursday': "پنج شنبه",
          "friday": "جمعه",
          'Scenario Name': 'نام سناریو',
          'To': ' تا ',
          'Start & End Period': 'بازه شروع و پایان',
          'Start Time': 'زمان شروع',
          'End Time': 'زمان پایان',
          'Duration': 'مدت زمان',
          'Start': 'شروع',
          'Every Day': 'هر روز',
          'Choose Days': 'انتخاب روزها',
          'Choose Devices': 'انتخاب عملگرها',
          "Manage Scenario": "مدیریت سناریوها",
          "Device Type": "نوع دستگاه",
          "Category": "دسته بندی",
          'Irrigation Actuator': 'عملگر آبیاری',
          'Lighting Actuator': 'عملگر روشنایی',
          'Irrigation Sensor': 'سنسور آبیاری',
          'Lighting Sensor': 'سنسور روشنایی',
          'Actuator': 'عملگر',
          'TYPE': 'نوع',
          'Sensor': 'سنسور',
          'Edit Device': 'ویرایش دستگاه',
          'New Device': 'دستگاه جدید',
          'MacAddress': 'شناسه دستگاه',
          'On': 'روشن',
          'Off': 'خاموش',
          'New Scenario': 'سناریو جدید',
          'Manual': 'دستی',
          'Smart': 'هوشمند',
          'Automatic': 'خودکار',
          'Type': 'نوع',
          'Mac': 'شناسه دستگاه',
          'Add Garden': 'اضافه کردن بوستان',
          'Name': 'نام',
          'DeviceCount': 'تعداد دستگاه ها',
          'Settings': 'تنظیمات',
          'Optional': '(اختیاری)',
          'PhoneNumber': 'شماره موبایل',
          'NationalCode': 'کد ملی',
          'FirstName': 'نام',
          'LastName': 'نام خانوادگی',
          'Email': 'ایمیل',
          'Confirm': 'تایید',
          'Logout': 'خروج از حساب کاربری',
          'Loading': 'صبر کنید',
          'Failed': 'ناموفق',
          'Success': 'موفق',
          'UserName': 'نام کاربری',
          'Password': 'گذرواژه',
          'Login': 'ورود',
          'Disabled': 'غیرفعال',
          'Muted': 'بی صدا',
          'Enabled': 'فعال',
          'Status': 'وضعیت',
          'No information recorded': ' - ',
          'Shahrino': 'شهرینو',
          'Access': 'دسترسی ها',
          'Gardens': 'بوستان ها',
          'Transportation': 'حمل و نقل',
          'Irrigation': 'آبیاری',
          'Multi-floor parking': 'پارکینگ طبقاتی',
          'Park Lighting': 'روشنایی بوستان',
          'passages Lighting': 'معابر روشنایی',
          'CCTV': 'دوربین مداربسته',
          'Air purification': 'پایش وضعیت هوا',
          'edit': 'ویرایش',
          'delete': 'حذف',
          'Reports': 'گزارشات',
          'Profile': 'پروفایل',
          'There are no items to display': "هیچ موردی برای نمایش وجود ندارد",
          'Address': 'آدرس',
          'Lighting': 'روشنایی',
          'Area': 'مساحت',
          'List': 'لیست',
          'Scenarios': 'سناریو ها',
          'Scenario': 'سناریو',
          "Available devices" : 'دستگاه های موجود',
          'Devices': 'دستگاه ها',
          'Device': 'دستگاه',
          'Number of devices': 'تعداد دستگاه ها',
          'designed and developed by iot':
              'طراحی و توسعه توسط شرکت هوشمندنگار – 2022'
        },
      };
}
